### PR TITLE
Now possible to overload compression level for managed compressions

### PR DESCRIPTION
**Pull request by dxdjgl**

### CODE REVIEW

**Review by aloneguid — CHANGES_REQUESTED** [review]
Seems like compression level will only apply to brotli (but not on .net standard 2.0) and gzip. It's inconsistent, maybe worth propagating across all the compression algorithms.

**Comment by dxdjgl** [comment]
The changes made in native code will change the compression level from previous versions.
The reason for the ticket created on parquet.net which lead to this changes is due to a change in compression ratio between version 3.10 and 4.3, the equipment does not have the additional processing power to handle this, but it does have disk space.

So I would be more than happy if I would be able to change compression ratio for gzip only

**Comment by aloneguid** [comment]
Build failing sorry. I'll help when I get to my PC if you need it.

**Comment by dxdjgl** [comment]
> Build failing sorry. I'll help when I get to my PC if you need it.

Sorry forgot to add parameter to the function signature, but added the description.
I cant build the cpp code, due to my environment, but I think it should be okay now.

**Comment by aloneguid** [comment]
LGTM, thank you!

**Pull request merged**
