### PR TITLE
IronCompressResult: add CreateMemoryStream()

### PR DESCRIPTION
**Pull request by nodakai**
Sorry I haven't even tried building, but I hope you get the idea... I want to call methods like this https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/MTransferUtilityUploadAsyncStreamStringStringCancellationToken.html in a zero-copy manner

### CODE REVIEW

**Comment by aloneguid** [comment]
Thanks! It might be confusing as it's not a real streaming. Maybe rename it to `CreateMemoryStream()` to be clear what it does?

**Comment by nodakai** [comment]
makes sense, renamed the method (also fixed a poor bug in it which did fail to compile)

**Comment by nodakai** [comment]
Can you try running GH Actions again @aloneguid

**Comment by nodakai** [comment]
Hi @aloneguid are you open to merging this PR?

**Comment by nodakai** [comment]
Hi @aloneguid do you think this PR is in a good shape for merging?

**Comment by nodakai** [comment]
Hi @aloneguid you have a few quick minutes to review this patch?

**Pull request closed without merging**
