### PR TITLE
Automatically use native implementation if available, then fallback to managed

### PR DESCRIPTION
**Pull request by aloneguid**

### CODE REVIEW

**Comment by dxdjgl** [comment]
Your is_supported() does not consider for instance 32 bit windows, that is why the dll missing exception should also be considered.

**Comment by aloneguid** [comment]
but i will call `ping()` before that, c# code will follow in a few minutes

**Comment by dxdjgl** [comment]
Okay, but I think you need to handle Dll missing exception since 32 bit native dll does not exist, so both your ping and is_supported will fail with an DLL missing exception.

**Comment by aloneguid** [comment]
they will check `IsNativeLibraryAvailable` so shouldn't

**Comment by aloneguid** [comment]
@dxdjgl ok i think it's ready, what do you think?

**Comment by dxdjgl** [comment]
Unfortunately as far as I can see you cant catch DllNotFoundException directly you need to catch AggregateException see below.
ERROR - xxxx - System.AggregateException: One or more errors occurred. ---> System.DllNotFoundException: Unable to load DLL 'nironcompress': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at IronCompress.Native.compress(Boolean compress, Int32 codec, Byte* inputBuffer, Int32 inputBufferSize, Byte* outputBuffer, Int32* outputBufferSize)

**Comment by aloneguid** [comment]
I think AggregateException is thrown by some downstream async method - i should be able to catch it in synchronous call for sure?

**Comment by aloneguid** [comment]
As you raised performance issues, it makes me think gzip native implementation can be also good (at the moment it's managed from .net) but that's another ticket.

**Comment by aloneguid** [comment]
need to do some microbenchmarking to see

**Comment by dxdjgl** [comment]
Think you are right, but we also need to consider System.BadImageFormatException
Unhandled Exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at IronCompress.Native.compress(Boolean compress, Int32 codec, Byte* inputBuffer, Int32 inputBufferSize, Byte* outputBuffer, Int32* outputBufferSize, Int32 compressionLevel)

**Comment by dxdjgl** [comment]
> As you raised performance issues, it makes me think gzip native implementation can be also good (at the moment it's managed from .net) but that's another ticket.

That would be fantastic.

**Comment by dxdjgl** [comment]
@aloneguid what do you think about the changes made to Parquet.net for compression level?

**Comment by dxdjgl** [comment]
With you last push 65a9187c111e10f8e4f1eb81790a55bc58d1d630 I think it looks great.

**Comment by aloneguid** [comment]
> @aloneguid what do you think about the changes made to Parquet.net for compression level?

Getting there now ;) If you're happy i'm merging and releasing this.

**Pull request merged**
