### PR TITLE
Make it optional to use managed compressions

### PR DESCRIPTION
**Pull request by dxdjgl**
Make it optional to use managed compressions, from for instance Parquet.net(to increase performance).

### CODE REVIEW

**Comment by dxdjgl** [comment]
@aloneguid I dont know why the tests are failing, no changes where made to the native code at all

**Comment by dxdjgl** [comment]
@aloneguid conflicts now solved should be ready to go.

**Comment by aloneguid** [comment]
just trying something in #13

**Comment by aloneguid** [comment]
closing in favour of #13, thanks for your help on this!

**Pull request closed without merging**
